# Generated by Django 3.2.8 on 2024-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.AlterModelOptions(
            name='genericfile',
            options={'verbose_name': 'file', 'verbose_name_plural': 'file'},
        ),
        migrations.AlterField(
            model_name='recyclefile',
            name='origin_path',
            field=models.CharField(max_length=500, verbose_name='origin_path'),
        ),
        migrations.AlterField(
            model_name='rolelimit',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='value'),
        ),
    ]
